# Keystone Auth
#KEYSTONE_URL=<KEYSTONE_URL>
#USERNAME=<USERNAME>
#PASSWORD=<PASSWORD>
#USER_DOMAIN_ID=<USER_DOMAIN_ID>
#PROJECT_NAME=<PROJECT_NAME>
#PROJECT_DOMAIN_ID=<PROJECT_DOMAIN_ID>

# VNF Heal API
#PROTOCOL=<PROTOCOL>
#HOST=<HOST>
#PORT=<PORT>
#API_VERSION=<API_VERSION>
#VNF_INSTANCE_ID=<VNF_INSTANCE_ID>
#USER_AGENT=<USER_AGENT>
#API_VERSION_HEADER=<API_VERSION_HEADER>

# Keystone Auth
KEYSTONE_URL=http://localhost/identity/v3/auth/tokens
USERNAME=nfv_user
PASSWORD=devstack
USER_DOMAIN_ID=default
PROJECT_NAME=nfv
PROJECT_DOMAIN_ID=default

# VNF Heal API
PROTOCOL=http
HOST=10.0.0.108
PORT=9890
API_VERSION=v2
VNF_INSTANCE_ID=9921c650-659e-4780-89df-2c4c0d0e2c0a
USER_AGENT=python-tackerclient
API_VERSION_HEADER=2.0.0

CAUSE=healing
ALL_PARAM=false
VNFC_INPUT=ODU1-odu1-vnf9921c650659e478089df2c4c0d0e2c0a-b7cf57b96-m6drn
